#!/bin/sh
REPOS="$1"
REV="$2"
TRAC_ENV='/var/www/trac.openmicroscopy.org.uk/agilo/'
REPO="test1"
/usr/bin/trac-admin "$TRAC_ENV" changeset added "$REPO" "$1" "$2"
/homes/jmoore/hooks.git/agilo_svn_hook_commit.py -R "$REPO" -s post -e "$TRAC_ENV" -r "$REV" || exit 1

