#!/bin/sh
REPOS="$1"
REV="$2"
TRAC_ENV='/var/www/trac.openmicroscopy.org.uk/agilo/'
/usr/bin/trac-admin "$TRAC_ENV" changeset added "$1" "$2"
/homes/jmoore/hooks.git/agilo_svn_hook_commit.py -R test1 -s post -e "$TRAC_ENV" -r "$REV" || exit 1

